name: pocket-js-server

services: 
  pg: 
    image: bitnami/postgresql:13.16.0
    ports:
      - '5432:5432'
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inorbit

  backend:
    build: .
    depends_on:
      - pg
    env_file:
      - .env
    command: >
      sh -c "
      until nc -z pg 5432; do
        echo 'Esperando o PostgreSQL iniciar...';
        sleep 1;
      done;
      echo 'PostgreSQL está pronto, executando as migrações e seeds...';
      dotenv -e .env -- npx drizzle-kit migrate &&
      dotenv -e .env -- npx tsx src/db/seed.ts &&
      dotenv -e .env -- npx tsx watch src/http/server.ts
      "
    ports:
      - "3333:3333"

volumes:
  postgres-data: